// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/productnoteusecase/create_product_note_usecase.go

// Package mockproductnoteusecase is a generated GoMock package.
package mockproductnoteusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	productnoteinput "github.com/onituka/agile-project-management/project-management/usecase/productnoteusecase/productnoteinput"
	productnoteoutput "github.com/onituka/agile-project-management/project-management/usecase/productnoteusecase/productnoteoutput"
)

// MockCreateProductNoteUsecase is a mock of CreateProductNoteUsecase interface.
type MockCreateProductNoteUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateProductNoteUsecaseMockRecorder
}

// MockCreateProductNoteUsecaseMockRecorder is the mock recorder for MockCreateProductNoteUsecase.
type MockCreateProductNoteUsecaseMockRecorder struct {
	mock *MockCreateProductNoteUsecase
}

// NewMockCreateProductNoteUsecase creates a new mock instance.
func NewMockCreateProductNoteUsecase(ctrl *gomock.Controller) *MockCreateProductNoteUsecase {
	mock := &MockCreateProductNoteUsecase{ctrl: ctrl}
	mock.recorder = &MockCreateProductNoteUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateProductNoteUsecase) EXPECT() *MockCreateProductNoteUsecaseMockRecorder {
	return m.recorder
}

// CreateProductNote mocks base method.
func (m *MockCreateProductNoteUsecase) CreateProductNote(ctx context.Context, in *productnoteinput.CreateProductNoteInput) (*productnoteoutput.CreateProductNoteOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductNote", ctx, in)
	ret0, _ := ret[0].(*productnoteoutput.CreateProductNoteOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductNote indicates an expected call of CreateProductNote.
func (mr *MockCreateProductNoteUsecaseMockRecorder) CreateProductNote(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductNote", reflect.TypeOf((*MockCreateProductNoteUsecase)(nil).CreateProductNote), ctx, in)
}
