// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/productnoteusecase/fetch_product_note_by_id_usecase.go

// Package mockproductnoteusecase is a generated GoMock package.
package mockproductnoteusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	productnoteinput "github.com/onituka/agile-project-management/project-management/usecase/productnoteusecase/productnoteinput"
	productnoteoutput "github.com/onituka/agile-project-management/project-management/usecase/productnoteusecase/productnoteoutput"
)

// MockFetchProductNoteByIDUsecase is a mock of FetchProductNoteByIDUsecase interface.
type MockFetchProductNoteByIDUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFetchProductNoteByIDUsecaseMockRecorder
}

// MockFetchProductNoteByIDUsecaseMockRecorder is the mock recorder for MockFetchProductNoteByIDUsecase.
type MockFetchProductNoteByIDUsecaseMockRecorder struct {
	mock *MockFetchProductNoteByIDUsecase
}

// NewMockFetchProductNoteByIDUsecase creates a new mock instance.
func NewMockFetchProductNoteByIDUsecase(ctrl *gomock.Controller) *MockFetchProductNoteByIDUsecase {
	mock := &MockFetchProductNoteByIDUsecase{ctrl: ctrl}
	mock.recorder = &MockFetchProductNoteByIDUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetchProductNoteByIDUsecase) EXPECT() *MockFetchProductNoteByIDUsecaseMockRecorder {
	return m.recorder
}

// FetchProductNoteByID mocks base method.
func (m *MockFetchProductNoteByIDUsecase) FetchProductNoteByID(ctx context.Context, in *productnoteinput.FetchProductNoteByIDInput) (*productnoteoutput.FetchProductNoteByIDOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProductNoteByID", ctx, in)
	ret0, _ := ret[0].(*productnoteoutput.FetchProductNoteByIDOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchProductNoteByID indicates an expected call of FetchProductNoteByID.
func (mr *MockFetchProductNoteByIDUsecaseMockRecorder) FetchProductNoteByID(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProductNoteByID", reflect.TypeOf((*MockFetchProductNoteByIDUsecase)(nil).FetchProductNoteByID), ctx, in)
}
