name: Swagger change notification
on:
# TODO: 動作確認の為、トリガーをpull_requestとする。
#  push:
#    branches:
#      - main
  pull_request:
    paths:
      - pm/swagger/**
      - .github/workflows/swagger-notify.yaml

jobs:
  notify:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Swagger notify
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Swagger更新通知
          fields: repo,message,commit,author
          text: 'swagger更新！'
          mention: 'here'
          if_mention: 'success'
          channel: '#swagger_notify'
          icon_emoji: ':octocat:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
